name: Core Testing

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

env:
  CACHE_NUMBER: 1  # increase to reset cache manually

jobs:
  foundation:

    strategy:
      matrix:
        python-version: [3.9]
    defaults:
      run:
        shell: bash -l {0}
    name: linux-64-py${{ matrix.python-version }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Graphviz
        uses: ts-graphviz/setup-graphviz@v2

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          # Install a specific version of uv.
          version: "0.5.11"

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install emat
        run: |
          uv sync --all-extras --dev

      - name: Setup DynamoDB Local
        uses: rrainn/dynamodb-action@v2.0.1
        with:
          dbPath: # undefined by default, if this is undefined inMemory will be used
          sharedDb: # undefined by default
          delayTransientStatuses: # undefined by default
          optimizeDbBeforeStartup: # undefined by default
          port: 8123
          cors: '*'

      - name: Test EMAT
        run: |
          uv run pytest .

