name: Core Testing

on:
  push:
    branches:
      - '*'

  pull_request:
    branches:
      - '*'

env:
  CACHE_NUMBER: 1  # increase to reset cache manually

jobs:
  foundation:

    strategy:
      matrix:
        python-version: [3.9]
    defaults:
      run:
        shell: bash -l {0}
    name: linux-64-py${{ matrix.python-version }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-version: latest
          environment-file: conda-envs/EMAT-DEV.yml
          python-version: ${{ matrix.python-version }}
          activate-environment: testing-env
          auto-activate-base: false
          auto-update-conda: false

      - name: Install emat
        # installing without dependencies is faster, we trust that all needed dependencies
        # are in the conda environment defined above.  Also, this avoids pip getting
        # confused and reinstalling tables (pytables).
        run: |
          python -m pip install . --no-deps

      - name: Conda checkup
        run: |
          conda info -a
          conda list

      - name: Setup DynamoDB Local
        uses: rrainn/dynamodb-action@v2.0.1
        with:
          dbPath: # undefined by default, if this is undefined inMemory will be used
          sharedDb: # undefined by default
          delayTransientStatuses: # undefined by default
          optimizeDbBeforeStartup: # undefined by default
          port: 8123
          cors: '*'

      - name: Test EMAT
        run: |
          python -m pytest .

